### ISSUE TITLE
Custom rights on mounts and config files

### ISSUE THREAD

**Issue by Tuxem** [stackhpc/ansible-role-beegfs#58]
Allow custom rights

```
- name: Ensure the BeeGFS mount point exists
  file:
    mode: 0755
    path: "{{ client_path }}"
    state: directory
  become: true
  notify: Restart BeeGFS client service

- name: Copy over beegfs-mounts config file
  template:
    src: beegfs-mounts.conf.j2
    dest: /etc/beegfs/beegfs-mounts.conf
    mode: 0644
  become: true
  notify: Restart BeeGFS client service

- name: Make of copy of BeeGFS client config file if it doesn't exist
  copy:
    mode: 0644
    remote_src: true
    src: /etc/beegfs/beegfs-client.conf
    dest: "/etc/beegfs/{{ beegfs_client_config_file }}"
    force: false
  become: true
  when: beegfs_client_scope_config | bool
  notify: Restart BeeGFS client service

```

For security, it bight be needed to remove world rights, maybe having variables :
- beegfs_client_config_mode
- beegfs_client_mount_mode
